// Base File
#include "zscript/HDReenforcements/base/zombiemen/0_BASE.zsc"
// Other includes for specific functions/categories of class changes. 
#include "zscript/HDReenforcements/base/zombiemen/overrides.zsc"
#include "zscript/HDReenforcements/base/zombiemen/a_hdaim.zsc"
#include "zscript/HDReenforcements/base/zombiemen/a_hdforget.zsc"
#include "zscript/HDReenforcements/base/zombiemen/a_hdturn.zsc"
#include "zscript/HDReenforcements/base/zombiemen/a_hddie.zsc"

// Subclasses
#include "zscript/HDReenforcements/base/zombiemen/revolver/0_INCLUDE.zsc"